---

- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

- name: Provisioning {{ project_name }}
  hosts: {{ hosts }}
  become: {{ sudo }}
  vars_files:
    - vars/main.yml
{% for role in vars_files %}
    - vars/{{ role }}.yml
{% endfor %}

  roles:
{% for role in roles %}
{% if role != 'ubuntu-xdebug' %}
    - {{ role }}
{% endif %}
{% endfor %}

{% if 'ubuntu-xdebug' in roles %}
- name: Vagrant provisioning
  hosts: vagrant
  become: yes
  gather_facts: true
  roles:
   - ubuntu-xdebug
{% endif %}
